name: qml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py27_0
  - clang=8.0.1=h770b8ee_1
  - clang-tools=8.0.1=h770b8ee_1
  - clangdev=8.0.1=h770b8ee_1
  - clangxx=8.0.1=1
  - icu=64.2=h6de7cb9_1
  - jpeg=9c=h1de35cc_1001
  - libclang=8.0.1=h770b8ee_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libiconv=1.15=h01d97ff_1005
  - libllvm8=8.0.1=h770b8ee_0
  - libpng=1.6.37=h2573ce8_0
  - libxml2=2.9.9=h12c6b28_5
  - libxslt=1.1.33=h320ff13_0
  - llvm-tools=8.0.1=0
  - llvmdev=8.0.1=h770b8ee_0
  - ncurses=6.1=h0a44026_1
  - nspr=4.20=h0a44026_1000
  - nss=3.46=h39b4b1f_0
  - openssl=1.1.1c=h01d97ff_0
  - pip=19.2.2=py27_0
  - pyside2=5.12.4=py27h9cca949_0
  - python=2.7.15=h8f8e585_6
  - qt=5.12.5=h1b46049_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.0.1=py27_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.4=py27_0
  - xz=5.2.4=h1de35cc_1001
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/vvzen/miniconda3/envs/qml-env

